import { useState } from "react";

type PictureSource = {
  srcset: string;
  type: string;
};

export type PictureData = {
  sources: PictureSource[];
  img: { src: string; w?: number; h?: number };
};

type Props = {
  data: PictureData;
  alt: string;
  ratio?: string;
  className?: string;
  imgClassName?: string;
  loading?: "eager" | "lazy";
  fetchPriority?: "high" | "low" | "auto";
  sizes?: string;
  fallbackLabel?: string;
};

/**
 * Renders a <picture> with AVIF/WebP sources (generated by vite-imagetools)
 * and a fallback <img>. Falls back to a labelled placeholder on error.
 */
export function Picture({
  data,
  alt,
  ratio = "aspect-[4/3]",
  className = "",
  imgClassName = "absolute inset-0 h-full w-full object-cover",
  loading = "lazy",
  fetchPriority,
  sizes = "(max-width: 640px) 100vw, (max-width: 1280px) 50vw, 800px",
  fallbackLabel,
}: Props) {
  const [failed, setFailed] = useState(false);
  return (
    <div
      className={`relative ${ratio} w-full overflow-hidden bg-foreground/[0.04] ${className}`}
      role="img"
      aria-label={alt}
    >
      {!failed ? (
        <picture>
          {data.sources.map((s) => (
            <source key={s.type} srcSet={s.srcset} type={s.type} sizes={sizes} />
          ))}
          <img
            src={data.img.src}
            width={data.img.w}
            height={data.img.h}
            alt={alt}
            loading={loading}
            decoding="async"
            fetchPriority={fetchPriority}
            sizes={sizes}
            className={imgClassName}
            onError={() => setFailed(true)}
          />
        </picture>
      ) : (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 p-6 text-center">
          <span className="text-[10px] font-medium uppercase tracking-[0.3em] text-foreground/50">
            Image unavailable
          </span>
          <span className="font-display text-base font-semibold text-foreground/80 sm:text-lg">
            {fallbackLabel ?? alt}
          </span>
        </div>
      )}
    </div>
  );
}