/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SingerBookingIndiaRouteImport } from './routes/singer-booking-india'
import { Route as PanIndiaCelebrityBookingRouteImport } from './routes/pan-india-celebrity-booking'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as InfluencerBookingIndiaRouteImport } from './routes/influencer-booking-india'
import { Route as ComedianBookingIndiaRouteImport } from './routes/comedian-booking-india'
import { Route as CelebrityDjBookingRouteImport } from './routes/celebrity-dj-booking'
import { Route as CelebrityChargesRouteImport } from './routes/celebrity-charges'
import { Route as CelebrityBookingIndiaRouteImport } from './routes/celebrity-booking-india'
import { Route as BookShahRukhKhanRouteImport } from './routes/book-shah-rukh-khan'
import { Route as BookKareenaKapoorRouteImport } from './routes/book-kareena-kapoor'
import { Route as BookAliaBhattRouteImport } from './routes/book-alia-bhatt'
import { Route as BollywoodCelebrityBookingRouteImport } from './routes/bollywood-celebrity-booking'
import { Route as BollywoodActressBookingRouteImport } from './routes/bollywood-actress-booking'
import { Route as IndexRouteImport } from './routes/index'

const SingerBookingIndiaRoute = SingerBookingIndiaRouteImport.update({
  id: '/singer-booking-india',
  path: '/singer-booking-india',
  getParentRoute: () => rootRouteImport,
} as any)
const PanIndiaCelebrityBookingRoute =
  PanIndiaCelebrityBookingRouteImport.update({
    id: '/pan-india-celebrity-booking',
    path: '/pan-india-celebrity-booking',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerBookingIndiaRoute = InfluencerBookingIndiaRouteImport.update({
  id: '/influencer-booking-india',
  path: '/influencer-booking-india',
  getParentRoute: () => rootRouteImport,
} as any)
const ComedianBookingIndiaRoute = ComedianBookingIndiaRouteImport.update({
  id: '/comedian-booking-india',
  path: '/comedian-booking-india',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrityDjBookingRoute = CelebrityDjBookingRouteImport.update({
  id: '/celebrity-dj-booking',
  path: '/celebrity-dj-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrityChargesRoute = CelebrityChargesRouteImport.update({
  id: '/celebrity-charges',
  path: '/celebrity-charges',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrityBookingIndiaRoute = CelebrityBookingIndiaRouteImport.update({
  id: '/celebrity-booking-india',
  path: '/celebrity-booking-india',
  getParentRoute: () => rootRouteImport,
} as any)
const BookShahRukhKhanRoute = BookShahRukhKhanRouteImport.update({
  id: '/book-shah-rukh-khan',
  path: '/book-shah-rukh-khan',
  getParentRoute: () => rootRouteImport,
} as any)
const BookKareenaKapoorRoute = BookKareenaKapoorRouteImport.update({
  id: '/book-kareena-kapoor',
  path: '/book-kareena-kapoor',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAliaBhattRoute = BookAliaBhattRouteImport.update({
  id: '/book-alia-bhatt',
  path: '/book-alia-bhatt',
  getParentRoute: () => rootRouteImport,
} as any)
const BollywoodCelebrityBookingRoute =
  BollywoodCelebrityBookingRouteImport.update({
    id: '/bollywood-celebrity-booking',
    path: '/bollywood-celebrity-booking',
    getParentRoute: () => rootRouteImport,
  } as any)
const BollywoodActressBookingRoute = BollywoodActressBookingRouteImport.update({
  id: '/bollywood-actress-booking',
  path: '/bollywood-actress-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bollywood-actress-booking': typeof BollywoodActressBookingRoute
  '/bollywood-celebrity-booking': typeof BollywoodCelebrityBookingRoute
  '/book-alia-bhatt': typeof BookAliaBhattRoute
  '/book-kareena-kapoor': typeof BookKareenaKapoorRoute
  '/book-shah-rukh-khan': typeof BookShahRukhKhanRoute
  '/celebrity-booking-india': typeof CelebrityBookingIndiaRoute
  '/celebrity-charges': typeof CelebrityChargesRoute
  '/celebrity-dj-booking': typeof CelebrityDjBookingRoute
  '/comedian-booking-india': typeof ComedianBookingIndiaRoute
  '/influencer-booking-india': typeof InfluencerBookingIndiaRoute
  '/newsroom': typeof NewsroomRoute
  '/pan-india-celebrity-booking': typeof PanIndiaCelebrityBookingRoute
  '/singer-booking-india': typeof SingerBookingIndiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bollywood-actress-booking': typeof BollywoodActressBookingRoute
  '/bollywood-celebrity-booking': typeof BollywoodCelebrityBookingRoute
  '/book-alia-bhatt': typeof BookAliaBhattRoute
  '/book-kareena-kapoor': typeof BookKareenaKapoorRoute
  '/book-shah-rukh-khan': typeof BookShahRukhKhanRoute
  '/celebrity-booking-india': typeof CelebrityBookingIndiaRoute
  '/celebrity-charges': typeof CelebrityChargesRoute
  '/celebrity-dj-booking': typeof CelebrityDjBookingRoute
  '/comedian-booking-india': typeof ComedianBookingIndiaRoute
  '/influencer-booking-india': typeof InfluencerBookingIndiaRoute
  '/newsroom': typeof NewsroomRoute
  '/pan-india-celebrity-booking': typeof PanIndiaCelebrityBookingRoute
  '/singer-booking-india': typeof SingerBookingIndiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bollywood-actress-booking': typeof BollywoodActressBookingRoute
  '/bollywood-celebrity-booking': typeof BollywoodCelebrityBookingRoute
  '/book-alia-bhatt': typeof BookAliaBhattRoute
  '/book-kareena-kapoor': typeof BookKareenaKapoorRoute
  '/book-shah-rukh-khan': typeof BookShahRukhKhanRoute
  '/celebrity-booking-india': typeof CelebrityBookingIndiaRoute
  '/celebrity-charges': typeof CelebrityChargesRoute
  '/celebrity-dj-booking': typeof CelebrityDjBookingRoute
  '/comedian-booking-india': typeof ComedianBookingIndiaRoute
  '/influencer-booking-india': typeof InfluencerBookingIndiaRoute
  '/newsroom': typeof NewsroomRoute
  '/pan-india-celebrity-booking': typeof PanIndiaCelebrityBookingRoute
  '/singer-booking-india': typeof SingerBookingIndiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bollywood-actress-booking'
    | '/bollywood-celebrity-booking'
    | '/book-alia-bhatt'
    | '/book-kareena-kapoor'
    | '/book-shah-rukh-khan'
    | '/celebrity-booking-india'
    | '/celebrity-charges'
    | '/celebrity-dj-booking'
    | '/comedian-booking-india'
    | '/influencer-booking-india'
    | '/newsroom'
    | '/pan-india-celebrity-booking'
    | '/singer-booking-india'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bollywood-actress-booking'
    | '/bollywood-celebrity-booking'
    | '/book-alia-bhatt'
    | '/book-kareena-kapoor'
    | '/book-shah-rukh-khan'
    | '/celebrity-booking-india'
    | '/celebrity-charges'
    | '/celebrity-dj-booking'
    | '/comedian-booking-india'
    | '/influencer-booking-india'
    | '/newsroom'
    | '/pan-india-celebrity-booking'
    | '/singer-booking-india'
  id:
    | '__root__'
    | '/'
    | '/bollywood-actress-booking'
    | '/bollywood-celebrity-booking'
    | '/book-alia-bhatt'
    | '/book-kareena-kapoor'
    | '/book-shah-rukh-khan'
    | '/celebrity-booking-india'
    | '/celebrity-charges'
    | '/celebrity-dj-booking'
    | '/comedian-booking-india'
    | '/influencer-booking-india'
    | '/newsroom'
    | '/pan-india-celebrity-booking'
    | '/singer-booking-india'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BollywoodActressBookingRoute: typeof BollywoodActressBookingRoute
  BollywoodCelebrityBookingRoute: typeof BollywoodCelebrityBookingRoute
  BookAliaBhattRoute: typeof BookAliaBhattRoute
  BookKareenaKapoorRoute: typeof BookKareenaKapoorRoute
  BookShahRukhKhanRoute: typeof BookShahRukhKhanRoute
  CelebrityBookingIndiaRoute: typeof CelebrityBookingIndiaRoute
  CelebrityChargesRoute: typeof CelebrityChargesRoute
  CelebrityDjBookingRoute: typeof CelebrityDjBookingRoute
  ComedianBookingIndiaRoute: typeof ComedianBookingIndiaRoute
  InfluencerBookingIndiaRoute: typeof InfluencerBookingIndiaRoute
  NewsroomRoute: typeof NewsroomRoute
  PanIndiaCelebrityBookingRoute: typeof PanIndiaCelebrityBookingRoute
  SingerBookingIndiaRoute: typeof SingerBookingIndiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/singer-booking-india': {
      id: '/singer-booking-india'
      path: '/singer-booking-india'
      fullPath: '/singer-booking-india'
      preLoaderRoute: typeof SingerBookingIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pan-india-celebrity-booking': {
      id: '/pan-india-celebrity-booking'
      path: '/pan-india-celebrity-booking'
      fullPath: '/pan-india-celebrity-booking'
      preLoaderRoute: typeof PanIndiaCelebrityBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer-booking-india': {
      id: '/influencer-booking-india'
      path: '/influencer-booking-india'
      fullPath: '/influencer-booking-india'
      preLoaderRoute: typeof InfluencerBookingIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comedian-booking-india': {
      id: '/comedian-booking-india'
      path: '/comedian-booking-india'
      fullPath: '/comedian-booking-india'
      preLoaderRoute: typeof ComedianBookingIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity-dj-booking': {
      id: '/celebrity-dj-booking'
      path: '/celebrity-dj-booking'
      fullPath: '/celebrity-dj-booking'
      preLoaderRoute: typeof CelebrityDjBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity-charges': {
      id: '/celebrity-charges'
      path: '/celebrity-charges'
      fullPath: '/celebrity-charges'
      preLoaderRoute: typeof CelebrityChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity-booking-india': {
      id: '/celebrity-booking-india'
      path: '/celebrity-booking-india'
      fullPath: '/celebrity-booking-india'
      preLoaderRoute: typeof CelebrityBookingIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-shah-rukh-khan': {
      id: '/book-shah-rukh-khan'
      path: '/book-shah-rukh-khan'
      fullPath: '/book-shah-rukh-khan'
      preLoaderRoute: typeof BookShahRukhKhanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-kareena-kapoor': {
      id: '/book-kareena-kapoor'
      path: '/book-kareena-kapoor'
      fullPath: '/book-kareena-kapoor'
      preLoaderRoute: typeof BookKareenaKapoorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-alia-bhatt': {
      id: '/book-alia-bhatt'
      path: '/book-alia-bhatt'
      fullPath: '/book-alia-bhatt'
      preLoaderRoute: typeof BookAliaBhattRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bollywood-celebrity-booking': {
      id: '/bollywood-celebrity-booking'
      path: '/bollywood-celebrity-booking'
      fullPath: '/bollywood-celebrity-booking'
      preLoaderRoute: typeof BollywoodCelebrityBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bollywood-actress-booking': {
      id: '/bollywood-actress-booking'
      path: '/bollywood-actress-booking'
      fullPath: '/bollywood-actress-booking'
      preLoaderRoute: typeof BollywoodActressBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BollywoodActressBookingRoute: BollywoodActressBookingRoute,
  BollywoodCelebrityBookingRoute: BollywoodCelebrityBookingRoute,
  BookAliaBhattRoute: BookAliaBhattRoute,
  BookKareenaKapoorRoute: BookKareenaKapoorRoute,
  BookShahRukhKhanRoute: BookShahRukhKhanRoute,
  CelebrityBookingIndiaRoute: CelebrityBookingIndiaRoute,
  CelebrityChargesRoute: CelebrityChargesRoute,
  CelebrityDjBookingRoute: CelebrityDjBookingRoute,
  ComedianBookingIndiaRoute: ComedianBookingIndiaRoute,
  InfluencerBookingIndiaRoute: InfluencerBookingIndiaRoute,
  NewsroomRoute: NewsroomRoute,
  PanIndiaCelebrityBookingRoute: PanIndiaCelebrityBookingRoute,
  SingerBookingIndiaRoute: SingerBookingIndiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
